// @vitest-environment jsdom
import { afterEach, describe, expect, it, vi } from 'vitest';
import { renovationEditor } from '../../helpers/renovationEditor';
import { expectDefined, expectOk } from '../../helpers/domain';
import { settle, mountPlanEditorCanvas, runtimeOf } from '../../helpers/editor';
import { referenceWorkspace } from '../../harness/referenceWorkspace';
import { HARNESS_PLAN, harnessDeps } from '../../harness/planEditor';
import { WALL_LOOP } from '../../helpers/structure';
import { defer } from '../../helpers/async';
import { err, ok } from '../../../src/core/result/Result';
import { useSaveStateStore } from '../../../src/presentation/editor/save-state/save-state-store';
const mounted: Awaited<ReturnType<typeof renovationEditor>>[] = [];
const cleanups: (() => void)[] = [];
afterEach(() => { for (const rig of mounted.splice(0)) rig.unmount(); for (const cleanup of cleanups.splice(0)) cleanup(); });
async function setup() {
 const rig = await renovationEditor(true); mounted.push(rig);
 rig.changePlan(); await settle(); rig.runtime.renovation.focus(rig.room.id, 'materials'); await settle();
 return rig;
}
const failure = err({ category: 'Persistence' as const, code: 'test.offline', message: 'Read unavailable' });
describe('connected planning read-back recovery', () => {
 it('recovers an unavailable first planning baseline from the Inspector without writing or reacting to unrelated files', async () => {
  const workspace = referenceWorkspace(harnessDeps(), HARNESS_PLAN, true); await workspace.ready;
  const room = expectOk(await workspace.deps.commands.createZone.execute({ planId: workspace.plan.id, name: 'Unloaded room', zoneType: 'Room', geometry: { points: WALL_LOOP.walls.map(wall => wall.start) } })).zone.entity;
  const services = expectDefined(workspace.deps.commands.planning, 'planning'), read = vi.spyOn(services, 'read').mockResolvedValue(failure);
  const harness = await mountPlanEditorCanvas({ plan: HARNESS_PLAN, queries: workspace.deps.queries, commands: workspace.deps.commands, vault: workspace.deps.vault }); cleanups.push(() => harness.unmount());
  const runtime = runtimeOf(harness); runtime.renovation.focus(room.id, 'materials'); await settle();
  expect(runtime.planning.baseline.value).toBeNull(); expect(harness.wrapper.get('[role="alert"]').text()).toContain('could not');
  const calls = read.mock.calls.length, bytes = [...workspace.stack.vault.entries];
  harness.changeFile('Journal/unrelated.md'); await settle(); expect(read).toHaveBeenCalledTimes(calls);
  await harness.wrapper.get('[role="alert"] button').trigger('click'); await settle();
  expect(runtime.planning.baseline.value).toBeNull(); expect([...workspace.stack.vault.entries]).toEqual(bytes);
  read.mockRestore(); await harness.wrapper.get('[role="alert"] button').trigger('click'); await settle();
  expect(runtime.planning.baseline.value).not.toBeNull(); expect(runtime.writesBlocked.value).toBe(false);
  expect([...workspace.stack.vault.entries]).toEqual(bytes);
  await runtime.renovation.perspective('review'); await settle();
  const note = vi.spyOn(workspace.deps.commands, 'reviewNote'); await harness.wrapper.get('[data-rp-action="review-note"]').trigger('click'); await settle();
  expect(note).toHaveBeenCalledWith(workspace.plan.id, expect.stringContaining('No gaps found'));
 });
 it('keeps a renovation draft editable during recovery and does not replay its successful Plan write', async () => {
  const rig = await setup(), services = expectDefined(rig.deps.commands.planning, 'planning');
  const editing = rig.runtime.renovation.edit('existing', rig.room.id); await settle();
  const field = rig.wrapper.get<HTMLTextAreaElement>('[name="description"]');
  await field.setValue('Original oak boards'); field.element.focus();
  const read = vi.spyOn(services, 'read').mockResolvedValue(failure); rig.changePlan(); await settle();
  expect(field.element.readOnly).toBe(false); expect(document.activeElement).toBe(field.element);
  read.mockRestore(); await rig.wrapper.get('.rp-draft-recovery button').trigger('click'); await settle();
  expect(field.element.value).toBe('Original oak boards');
  const savePlan = rig.stack.plans.save.bind(rig.stack.plans);
  const save = vi.spyOn(rig.stack.plans, 'save').mockImplementation(async (...args) => {
   const result = await savePlan(...args); vi.spyOn(services, 'read').mockResolvedValue(failure); return result;
  });
  await rig.wrapper.get('[data-rp-form="renovation"]').trigger('submit');
  await rig.wrapper.get('[data-rp-form="renovation"]').trigger('submit'); await settle(); await editing;
  expect(save).toHaveBeenCalledOnce(); expect(rig.wrapper.text()).toContain('Saved · refresh needed');
  vi.mocked(services.read).mockRestore(); await rig.runtime.refreshProjection(); await rig.runtime.refreshProjection();
  expect(save).toHaveBeenCalledOnce(); expect(rig.runtime.writesBlocked.value).toBe(false);
  expect(rig.runtime.planning.baseline.value?.plan.entity.renovation?.subjects[0].existing?.description).toBe('Original oak boards');
 });
 it('retains the projection after one successful save, blocks unsafe history and retries only reads', async () => {
  const rig = await setup(), services = expectDefined(rig.deps.commands.planning, 'planning');
  await rig.wrapper.get('[data-rp-new-material]').trigger('click'); await settle();
  const asset = expectOk(await rig.stack.assets.listAll()).loaded.find(item => item.entity.unit === 'm2');
  await rig.wrapper.get('select[name="asset"]').setValue(expectDefined(asset, 'asset').entity.id);
  const before = rig.runtime.planning.baseline.value, save = vi.spyOn(rig.stack.requirements, 'save');
  const read = vi.spyOn(services, 'read').mockResolvedValue(failure);
  await rig.wrapper.get('[data-rp-form="planning"]').trigger('submit'); await settle();
  expect(save).toHaveBeenCalledTimes(1);
  expect(rig.runtime.planning.baseline.value).toBe(before);
  expect(rig.wrapper.text()).toContain('Saved · refresh needed');
  expect(rig.wrapper.find('[data-rp-form="planning"]').exists()).toBe(false);
  expect(rig.runtime.writesBlocked.value).toBe(true); expect(rig.runtime.canUndo.value).toBe(false);
  expect((await rig.runtime.dispatcher.undo()).ok).toBe(false);
  expect((await rig.runtime.dispatcher.redo()).ok).toBe(false);
  await rig.runtime.refreshProjection(); await rig.runtime.refreshProjection();
  expect(rig.wrapper.text()).toContain('Re-reading failed again'); expect(save).toHaveBeenCalledTimes(1);
  read.mockRestore(); await rig.runtime.refreshProjection(); await settle();
  expect(rig.runtime.planning.baseline.value?.materials).toHaveLength(1);
  expect(rig.runtime.writesBlocked.value).toBe(false); expect(rig.runtime.canUndo.value).toBe(true);
  expect(save).toHaveBeenCalledTimes(1);
 });
 it('keeps the focused draft through a background failure and exposes retry inside the modal', async () => {
  const rig = await setup(), services = expectDefined(rig.deps.commands.planning, 'planning');
  const source = vi.spyOn(rig.runtime, 'openPlanNote');
  await rig.wrapper.get('[data-rp-new-material]').trigger('click'); await settle();
  const field = rig.wrapper.get<HTMLInputElement>('input[name="waste"]');
  await field.setValue('17,5'); field.element.focus();
  const read = vi.spyOn(services, 'read').mockResolvedValue(failure);
  rig.changeCatalogue(); await settle();
  expect(document.activeElement).toBe(field.element); expect(field.element.value).toBe('17,5');
  expect(rig.wrapper.get('[data-rp-planning-apply]').attributes('disabled')).toBeDefined();
  const bytes = [...rig.stack.vault.entries];
  const pending = defer<Awaited<ReturnType<typeof services.read>>>(); read.mockReturnValueOnce(pending.promise);
  const calls = read.mock.calls.length;
  await rig.wrapper.get('.rp-draft-recovery button').trigger('click'); await settle();
  await rig.wrapper.get('.rp-draft-recovery button').trigger('click'); await settle();
  expect(read).toHaveBeenCalledTimes(calls + 1);
  await rig.wrapper.get('.rp-draft-recovery button:last-of-type').trigger('click');
  expect(source).toHaveBeenCalledOnce();
  pending.resolve(failure); await settle();
  expect([...rig.stack.vault.entries]).toEqual(bytes);
  read.mockRestore(); rig.wrapper.get<HTMLButtonElement>('.rp-draft-recovery button').element.focus();
  await rig.wrapper.get('.rp-draft-recovery button').trigger('click'); await settle();
  expect(document.activeElement).toBe(rig.wrapper.get('[name="target"]').element);
  expect(field.element.value).toBe('17,5'); expect(rig.wrapper.find('.rp-draft-recovery').exists()).toBe(false);
  rig.dialogs.resolve('cancel'); await settle(); expect([...rig.stack.vault.entries]).toEqual(bytes);
 });
 it('coalesces event bursts, ignores obsolete reads and never publishes after disposal', async () => {
  const rig = await setup(), services = expectDefined(rig.deps.commands.planning, 'planning');
  const before = expectDefined(rig.runtime.planning.baseline.value, 'baseline');
  const pending = defer<Awaited<ReturnType<typeof services.read>>>(), next = defer<Awaited<ReturnType<typeof services.read>>>();
  const read = vi.spyOn(services, 'read').mockReturnValueOnce(pending.promise).mockReturnValueOnce(next.promise);
  for (let index = 0; index < 100; index++) rig.changeCatalogue();
  await settle(); expect(read).toHaveBeenCalledTimes(1);
  expect(rig.runtime.planning.slow.value).toBe(false);
  await new Promise(resolve => { setTimeout(resolve, 310); });
  expect(rig.runtime.planning.slow.value).toBe(true);
  for (let index = 0; index < 100; index++) rig.changeCatalogue();
  pending.resolve(failure); await settle();
  expect(rig.runtime.planning.failed.value).toBe(false); expect(read).toHaveBeenCalledTimes(2);
  next.resolve(ok(before)); await settle(); expect(rig.runtime.planning.baseline.value).toBe(before);
  expect(rig.runtime.planning.slow.value).toBe(false);
  read.mockRejectedValueOnce(new Error('unexpected reader failure')); await rig.runtime.refreshProjection();
  expect(rig.runtime.planning.failed.value).toBe(true);
  await rig.runtime.refreshProjection(); expect(rig.runtime.planning.failed.value).toBe(false);
  const late = defer<Awaited<ReturnType<typeof services.read>>>(); read.mockReturnValueOnce(late.promise);
  const refresh = rig.runtime.refreshProjection(); await settle(); rig.unmount();
  late.resolve(failure); await refresh; await settle(); expect(rig.runtime.planning.failed.value).toBe(false);
 });
 it('does not treat a read as recovery from an uncompensated write', async () => {
  const rig = await setup(), save = useSaveStateStore(rig.pinia);
  save.markUnrecovered(); await settle();
  expect(rig.runtime.writesBlocked.value).toBe(true); expect(rig.runtime.canUndo.value).toBe(false);
  await rig.runtime.refreshProjection(); expect(rig.runtime.writesBlocked.value).toBe(true);
  expect(rig.wrapper.text()).toContain('could not be completed or undone');
 });
 it('does not start an Inspector query when spatial hydration finishes after closing the editor', async () => {
  const rig = await setup(), queries = rig.deps.queries, result = await queries.getPlan(rig.plan.id);
  const pending = defer<typeof result>(); vi.spyOn(queries, 'getPlan').mockReturnValueOnce(pending.promise);
  const refresh = vi.spyOn(rig.deps.commands.zoneInspector, 'execute');
  const reading = rig.runtime.refreshProjection(); await settle(); rig.unmount(); await reading;
  pending.resolve(result); await settle(); expect(refresh).not.toHaveBeenCalled();
 });
});
